### ISSUE TITLE
Support nesting paths

### ISSUE THREAD

**Issue by dinoboff** [smkamranqadri/vscode-bolt-language#3] opened 2017-08-27 10:01 UTC
Can you add support for [nested path](https://github.com/firebase/bolt/blob/master/samples/children.bolt)?

**Comment by smkamranqadri** [comment] 2017-08-27 22:18
Sure, I will look into it.

**Comment by esprehn** [comment] 2017-09-28 23:55
Any luck here? This makes it hard to edit a lot of rule files.

**Comment by smkamranqadri** [comment] 2017-09-29 09:49
Not yet, will look into by tomorrow.

**Comment by smkamranqadri** [comment] 2023-10-20 20:23
The issue is resolved in last version.
![Screenshot 2023-10-21 at 1 23 20 AM](https://github.com/smkamranqadri/vscode-bolt-language/assets/13115396/a2c0e1e8-35f8-4d4a-8796-185764c8dc8e)

**Closed as completed by smkamranqadri** 2023-10-20 20:23 UTC
Labels: hacktoberfest
